[package]
name = "evm"
version = "0.37.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
auto_impl = "1.0.1"
ethereum = { version = "0.14.0", default-features = false }
log = { version = "0.4.17", default-features = false }
primitive-types = { version = "0.12.1", default-features = false, features = ["rlp"] }
rlp = { version = "0.5.2", default-features = false }
sha3 = { version = "0.10.6", default-features = false }

# Optional dependencies
environmental = { version = "1.1.2", default-features = false, optional = true }
scale-codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"], optional = true }
serde = { version = "1.0.147", default-features = false, features = ["derive"], optional = true }

evm-core = { version = "0.37.0", path = "core", default-features = false }
evm-gasometer = { version = "0.37.0", path = "gasometer", default-features = false }
evm-runtime = { version = "0.37.0", path = "runtime", default-features = false }
mx-sc = { path= "../elrond-wasm-rs/framework/base", version = "0.38.0", features = ["alloc"] }
eltypes = { version = "0.1.0", path = "eltypes", default-features = false }

[dev-dependencies]
criterion = "0.4.0"
hex = "0.4.0"

[[bench]]
name = "loop"
harness = false

[features]
default = ["std"]
std = [
	"ethereum/std",
	"log/std",
	"primitive-types/std",
	"rlp/std",
	"sha3/std",
	"environmental/std",
	"scale-codec/std",
	"scale-info/std",
	"serde/std",
	"evm-core/std",
	"evm-gasometer/std",
	"evm-runtime/std",
]
with-codec = [
	"scale-codec",
	"scale-info",
	"primitive-types/codec",
	"primitive-types/scale-info",
	"ethereum/with-codec",
	"evm-core/with-codec",
]
with-serde = [
	"serde",
	"primitive-types/serde",
	"evm-core/with-serde",
	"ethereum/with-serde",
]
tracing = [
	"environmental",
	"evm-gasometer/tracing",
	"evm-runtime/tracing",
]

[workspace]
members = [
	"core",
	"gasometer",
	"runtime",
	"fuzzer",
]
